### ISSUE TITLE
Expired token check failing

### ISSUE THREAD

**Issue by Ylevo** [ArdaxHz/mupl#12]
Hey,

In oauth.py at line 135, a check for null is missing on the token argument, resulting in a crash when trying to split it. Happens on first run/when .mdauth doesn't exist.

**Comment by ArdaxHz** [comment]
What version are you using? That line of code isn't used on the latest release

**Comment by Ylevo** [comment]
Oh yeah it notified me of an update yesterday, and after updating logging in was broken. I noticed things were missing/moved around and I ended up pulling from the repo myself.

**Comment by ArdaxHz** [comment]
If you're on v1.1.1, it should all be working fine, there hasn't been any issues with that
