### ISSUE TITLE
Name format check fails with decimal chapter number

### ISSUE THREAD

**Issue by kouyo-quotient** [ArdaxHz/mupl#18]
It appears that if two numbers are input after the period, the format check fails and the chapter will not be uploaded, despite the API accepting more than one number after the period.

Format check fails
![image](https://github.com/ArdaxHz/mupl/assets/46226504/3262cbcb-b0ba-466d-a379-497cb49ad282)

Format check succeeds
![image](https://github.com/ArdaxHz/mupl/assets/46226504/aaf8e995-583f-43e2-9767-d486988fcef7)

**Comment by ArdaxHz** [comment]
Fixed in 52c8796
